spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&characterEncoding=utf-8
    type:  com.alibaba.druid.pool.DruidDataSource
    username: root
    password: cxp
    driver-class-name: com.mysql.cj.jdbc.Driver


#springÕûºÏmybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.offcn.pojo
